server.port=8083
spring.mongodb.uri=mongodb://localhost:27017/dinemaster_reservation

jwt.secret=${JWT_SECRET}
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access=DEBUG
management.endpoints.web.exposure.include=mappings,health
spring.security.oauth2.resourceserver.jwt.jws-algorithms=HS256

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
