server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/dinemaster_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MySQL120@

spring.mongodb.uri=mongodb://localhost:27017/dinemaster_db

app.jwtSecret=DineMasterSecretKeyForEncryption
app.jwtExpirationMs=86400000