spring.application.name=auth-service
spring.datasource.url=jdbc:mysql://localhost:3306/dinemaster_auth
spring.datasource.username=root
spring.datasource.password=MySQL120@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

